

services:
  web:
    build: .
    working_dir: /app
    volumes:

      - /app/node_modules
    ports:
      - "5500:5500"
    command: ["/bin/sh", "-c", "chmod +x wait-for-it.sh && ./wait-for-it.sh db:5432 -- npm run dev"]
    environment:
      - DATABASE_URL=postgres://postgres:anasomar12@db:5432/postgres
    depends_on:
      - db


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anasomar12
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/school_dump.sql:/docker-entrypoint-initdb.d/school_dump.sql:ro

volumes:
  pgdata:
